name: Build XMRig for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 2019

    - name: Install dependencies
      run: |
        choco install cmake git

    - name: Build XMRig
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Upload build artifact
      uses: actions/upload-artifact@latest  # Use the latest stable version
      with:
        name: xmrig-win
        path: build/xmrig/bin/Release/xmrig.exe
