name: Build XMRig for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2
      
    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        
    - name: Download XMRig dependencies
      run: |
        # Download the XMRig dependencies source
        Invoke-WebRequest -Uri "https://github.com/xmrig/xmrig-deps/archive/refs/tags/v25.06.16.zip" -OutFile "xmrig-deps.zip"
        Expand-Archive -Path "xmrig-deps.zip" -DestinationPath "C:\"
        # Rename the extracted folder to match expected structure
        Rename-Item -Path "C:\xmrig-deps-25.06.16" -NewName "xmrig-deps"
        # Verify the structure
        Get-ChildItem -Path "C:\xmrig-deps" -Recurse -Directory | Select-Object FullName
        
    - name: Build XMRig
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DXMRIG_DEPS=C:\xmrig-deps\msvc2022\x64
        cmake --build . --config Release
        
    - name: List build output
      run: |
        Get-ChildItem -Path "build" -Recurse -Filter "*.exe" | Select-Object FullName
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-win-x64
        path: build/Release/xmrig.exe
