name: Build XMRig Static Linux Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          build-essential \
          cmake \
          automake \
          libtool \
          autoconf
        # Display compiler versions
        gcc --version
        g++ --version
        cmake --version
        
    - name: Clone XMRig repository
      run: |
        git clone https://github.com/mian196/xmrig.git
        
    - name: Build static dependencies
      run: |
        cd xmrig/scripts
        ./build_deps.sh
        
    - name: Configure XMRig with static dependencies
      run: |
        mkdir -p xmrig/build
        cd xmrig/build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DXMRIG_DEPS=scripts/deps \
          -DCMAKE_C_FLAGS="-O3 -march=native -mtune=native -flto" \
          -DCMAKE_CXX_FLAGS="-O3 -march=native -mtune=native -flto"
        
    - name: Build optimized static XMRig
      run: |
        cd xmrig/build
        make -j$(nproc)
        
    - name: Verify static binary
      run: |
        echo "Checking if binary is statically linked:"
        file xmrig/build/xmrig
        echo "Dependencies (should be minimal for static binary):"
        ldd xmrig/build/xmrig || echo "Statically linked (no dynamic dependencies)"
        echo "Binary size:"
        ls -lh xmrig/build/xmrig
        echo "Testing binary:"
        ./xmrig/build/xmrig --help | head -20
        
    - name: Strip binary to reduce size
      run: |
        strip xmrig/build/xmrig
        echo "Stripped binary size:"
        ls -lh xmrig/build/xmrig
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-linux-ubuntu-static
        path: xmrig/build/xmrig
