name: Build XMRig for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version
      
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2  # Updated to v2
      
    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        
    - name: Install vcpkg and dependencies
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe install libuv:x64-windows openssl:x64-windows hwloc:x64-windows
        
    - name: Build XMRig
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_PREFIX_PATH=..\vcpkg\installed\x64-windows
        cmake --build . --config Release
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4  # Updated to latest version
      with:
        name: xmrig-win
        path: build/Release/xmrig.exe
